version: "3.9"

services:
  gpu:
    image: coedl/w2v2-pretrain
    volumes:
      - ${PWD}:/workspace
      - ${PWD}/tmp/cache:/root/.cache
    working_dir: /workspace
    entrypoint:
      - /bin/bash
    stdin_open: true
    tty: true
    ipc: host
    ulimits:
      memlock: '-1'
      stack: '67108864'
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
